specification/gp-connect-user-permissions.yaml
=> Error codes

specification/gp-connect-user-permissions.yaml
Updates as per [content guide](https://nhsd-confluence.digital.nhs.uk/display/APM/API+content+style+guide).
=> Update content to align to content guide

specification/gp-connect-user-permissions.yaml
=> Nhs number and ods code

azure/project.yml, ecs-proxies-deploy.yml, proxies/sandbox/apiproxy/policies/AssignMessage.AddAuthorization.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/targets/sandbox.xml, specification/gp-connect-user-permissions.yaml
=> AMB-1450 Fix Try This API feature on spec

azure/azure-pr-teardown-pipeline.yml
=> Teardown pipeline test

.github/workflows/continuous-disintegration.yml
=> AMB-1435: Added github action to trigger teardown

.github/workflows/continuous-disintegration.yml
=> Test amb 1435 pr teardown

.github/workflows/continuous-disintegration.yml
=> AMB-1435: Fixed pipeline name typo

.github/workflows/continuous-disintegration.yml
=> Debug comment

.github/workflows/continuous-disintegration.yml
=> Remove debug comment

tests/test_mock_provider.py
=> AMB-1434 PR Builds

.editorconfig, azure/azure-pr-teardown-pipeline.yml, azure/templates/remove-kvm-entry.yml
=> AMB-1435: Added PR Teardown pipeline

azure/templates/post-deploy.yml, tests/Makefile, tests/pytest.ini, tests/test_endpoints.py, tests/test_mock_provider_int.py
=> AMB-1512 Add int environment tests 

tests/example_loader.py, tests/test_endpoints.py
=> AMB-1511: Added test for external prism files

Makefile, azure/templates/post-deploy.yml, tests/test_endpoints.py
=> AMB-1512 Fixing int env tests

.dependabot/config.yml, package-lock.json, package.json
=> Amb 1549 configure depndabot

manifest_template.yml
=> AMB-1560 Fix Identity-service provider for OAuth

azure/templates/post-deploy.yml, token_validator/src/validate_access_token.py, token_validator/tests/test_validate_access_token.py
=> AMB-1485: Updated Keycloak URLs

proxies/live/apiproxy/policies/AssignMessage.AddInteractionID.xml, proxies/live/apiproxy/proxies/default.xml, tests/test_endpoints.py, tests/test_mock_provider.py, tests/test_mock_provider_int.py
=> AMB-1562 add interaction IDs to proxy flow

terraform/alb/target_group.tf
=>  AMB-1615-Fix-target-group-dependency-on-load-balancer 

specification/gp-connect-user-permissions.yaml
More thorough errors added for patient_not_found
=> extra errors added

azure/project.yml, specification/gp-connect-user-permissions.yaml
=> AMB-1610: Updated base path and server urls

specification/components/examples/PostResponseRejectedAppointments.yaml, specification/components/examples/RejectedRequestError.yaml, specification/components/schemas/BaseRequest.yaml, specification/components/schemas/ErrorResponse.yaml, specification/gp-connect-user-permissions.yaml
Small changes to move errors for rejection under 4XX.
=> PFS-160: Update User management to return OperationOutcome

README.md, terraform/README.md
=> AMB-1629 update README.md

specification/components/examples/RejectedRequestError.yaml, specification/components/schemas/ErrorResponse.yaml, specification/gp-connect-user-permissions.yaml
=> changes to error handling

azure/project.yml, specification/gp-connect-user-permissions.yaml, tests/Makefile
=> AMB-1693 rename base path

pyproject.toml, scripts/apigee_kvm.py, scripts/destroy_unused_workspaces.py, terraform/infra.tf
=> AMB-1846-writing-script-for-unused-workspaces-on-AWS

specification/gp-connect-user-permissions.yaml, terraform/cluster/ecs-logger.tf
AMB - 1563 - Updated the postman collection link in the yaml file
=> AMB 1563 - Updated the postman url for gp-connect-user-permission

specification/gp-connect-user-permissions.yaml
=> AMB 1563 - Updated the postman link URL in the specification file

proxies/live/apiproxy/proxies/default.xml
=> updated default condition

proxies/live/apiproxy/policies/ServiceCallout.AuthenticateAgainstGPC.xml, proxies/live/apiproxy/resources/jsc/GetGPCAuthCode.js, proxies/live/apiproxy/targets/target.xml
=> Updated auth variable

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, manifest_template.yml
=> Removed mock provider for prod

proxies/live/apiproxy/policies/ExtractVariables.ResponseVariables.xml, proxies/live/apiproxy/targets/target.xml, proxies/live/apiproxy/targets/targetdev.xml
=> updated error response handling

proxies/live/apiproxy/policies/AssignMessage.ODSNotFoundErrorResponse.xml, proxies/live/apiproxy/targets/target.xml, proxies/live/apiproxy/targets/targetdev.xml, tests/test_endpoints.py, tests/test_mock_provider.py, token_validator/tests/test_validate_access_token.py
=> added policy for ods not found scenario

README.md
=> dummy change to trigger pipeline
